<table class="table" id="data_table">
    <thead>
        <tr>
            <th>Hola</th>
            <th>Hola2</th>
            <th>Hola3</th>
            <th>Hola4</th>
            <th>Hola5</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
        </tr>
        <tr>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
        </tr>
        <tr>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
        </tr>
        <tr>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
        </tr>
        <tr>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
        </tr>
        <tr>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
        </tr>
        <tr>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
        </tr>
        <tr>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
        </tr>
        <tr>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
        </tr>
        <tr>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
        </tr>
        <tr>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
        </tr>
        <tr>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
        </tr>
        <tr>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
        </tr>
        <tr>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
        </tr>
        <tr>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
        </tr>
        <tr>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
        </tr>
        <tr>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
        </tr>
        <tr>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
        </tr>
        <tr>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
        </tr>
        <tr>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
        </tr>
        <tr>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
        </tr>
        <tr>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
        </tr>
        <tr>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
        </tr>
        <tr>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
        </tr>
        <tr>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
        </tr>
        <tr>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
        </tr>
        <tr>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
        </tr>
        <tr>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
        </tr>
        <tr>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
        </tr>
        <tr>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
        </tr>
        <tr>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
        </tr>
        <tr>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
        </tr>
        <tr>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
        </tr>
        <tr>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
        </tr>
        <tr>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
        </tr>
        <tr>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
            <td>Hola</td>
        </tr>
    </tbody>
</table>